name: Launcher

on:
  push:
    paths:
    - 'dist_cfg/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            build_cmd: "build-linux"

          - os: windows-latest
            build_cmd: "build-win"

    steps:
      - uses: actions/checkout@v2
        with:
          path: BYAR-Chobby

      - uses: actions/checkout@v2
        with:
          repository: gajop/spring-launcher
          path: spring-launcher

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Prepare folder structure
        run: |
          mkdir build
          cp spring-launcher/* -r build/
          cp BYAR-Chobby/dist_cfg/* -r build/src/
          [ -f build/src/bin/ ] && mv build/src/bin/* build/bin/
          [ -f build/src/files/ ] && mv build/src/files/* build/files/
          [ -f build/src/build/ ] && mv build/src/build/* build/build/
          exit 0

      - name: Make package.json
        run: |
          cd BYAR-Chobby
          export PACKAGE_VERSION=1.$(git rev-list --count HEAD).0
          cd ..
          node ./BYAR-Chobby/build/make_package_json.js build/package.json BYAR-Chobby/dist_cfg/config.json beyond-all-reason/BYAR-Chobby $PACKAGE_VERSION

      - name: Build
        run: |
          cd build
          npm ci
          npm run ${{ matrix.build_cmd }} -- --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}






